## Generar una lista de adjacencia random

In [15]:
import random
import numpy as np

In [16]:
def RandomAL(n, m):
    G = [None for _ in range(n)]
    numEdges = [0]*n
    for _ in range(m):
        numEdges[random.randint(0, n - 1)] += 1
    vertices = [i for i in range(n)]
    random.shuffle(vertices)
    for u in range(n):
        G[u] = random.sample(vertices, numEdges[u])

    return G

In [17]:
G = RandomAL(10,20)
for l in G:
    print(l)

[4, 3]
[0]
[]
[2]
[3, 5, 1, 8, 9]
[6, 4]
[8, 6]
[0, 8, 6]
[4]
[1, 6, 7]


## Generar una matriz de adjacencia random

In [18]:
def randomAM(n,m):
    G = np.zeros((n*n),dtype=int)
    G[:m] = 1
    random.shuffle(G)
    return G.reshape((n,n))

In [19]:
M = randomAM(10,20)
print(M)

[[0 0 0 0 0 1 0 1 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 1 1]]


## Algoritmo Exhaustivo

In [20]:
def revG(G):
    n = len (G)
    Grev = [[]for _ in range(n)]
    for u in range(n):
        for v in G[u]:
            Grev[v].append(u)
    return Grev

In [21]:
G = [[2], [0], [1,3],[]]

In [22]:
revG(G)

[[1], [2], [0], [2]]

In [23]:
def kosaraju(G):
    def dfs(g, u, f):
        visited[u]=True
        for v in g[u]:
            if not visited[v]:
                dfs(g, v,f)
        f.append(u)

    Grev = revG(G)
    n = len(G)
    visited = [False]*n
    f = []
    for u in range(n):
        if not visited[u]:
            dfs(Grev,u,f)
    ## Segunda parte
    visited = [False]*n
    cfc = []
    print(f)
    while f:
        u = f.pop()
        if not visited[u]:
            ncfc = []
            dfs(G,u,ncfc)
            cfc.append(ncfc)
    return cfc

In [24]:
kosaraju(G)

[2, 1, 0, 3]


[[3], [1, 2, 0]]