In [3]:
import numpy as np

In [1]:
def randomAM(n, m):
  matriz = np.array([1 if i < m else 0 for i in range (n * n)])
  np.random.shuffle(matriz)
  return matriz.reshape((n, n))

In [13]:
n = 5 # Tamaño de la matriz nxn
m = 2 # Numero de 1 en la matriz

In [22]:
np.random.seed(1981)
g = randomAM(n,m)
print(g)

[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


### Paso a Paso del Algoritmo

In [60]:
np.random.seed(1981) # Se genera una semilla aleatoria
a = [1 if i < m else 0 for i in range (n *n)] # Crea una lista de tamaño nxn y con m zeros
print(a)
a = np.array(a, dtype=int) # Lo convierte en un arreglo de enteros sin coma flotante
print(a)
np.random.shuffle(a) # Varia las posiciones del arreglo
print(a)
print(a.shape) # Imprime el 'tamaño de la matriz' (a,b), pero en nuestro caso imprimiria (nxn,) ---> que seria el numero de elementos en nuestra matriz
print(a.reshape((n,n))) # Imprime nuestra matriz siguiendo el formato que se entregue

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
(25,)
[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
(25,)
